name: LION Auto Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        env:
          # 这里引用你设置好的 Secret 名
          GH_TOKEN: ${{ secrets.HEXO_DEPLOY_TOKEN }}
        run: |
          git config --global user.name "lion-01cat"
          git config --global user.email "ba20240121@gmail.com"
          # 核心逻辑：生成静态文件并推送到 gh-pages 分支
          npx hexo clean
          npx hexo generate
          cd public
          git init
          git add .
          git commit -m "LION: Render from Nothing"
          # 使用 Token 强制推送到仓库的 gh-pages 分支
          git push --force https://${GH_TOKEN}@://github.com master:gh-pages
